title: Midnight Parrot
description: Midnight Parrot is CN-Shopkeeper's blog.
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight

url: https://cn-shopkeeper.github.io

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
